# Site settings
title:              Lila Smith
email:              lsmith2@olin.edu
description:        Lila Smith's Portfolio
# url:                "http://127.0.0.1:4000"
url:                "http://lila.engineer" 
baseurl:

# File structure settings
image_path:         /public/images
docs_path:          /public/other


# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
